# Azure DevOps Pipeline definition
pool: 
  name: Default
stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/StringLibrary/*.csproj'
- stage: Deploy
  jobs:
  - job: PackPush
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        packagesToPack: '**/StringLibrary/*.csproj'
        buildProperties: 'PackageId=Patrick_COMP367_Lab4_StringLibrary'
        versioningScheme: 'off'
    - task: DotNetCoreCLI@2
      inputs:
        command: custom
        custom: nuget
        arguments: 'push $(Build.ArtifactStagingDirectory)/**/*.nupkg --source https://pkgs.dev.azure.com/pneves7777/_packaging/pneves7777/nuget/v3/index.json --api-key az --skip-duplicate'